# app/config/config.yml
liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public/upload"
        cache_prefix: "media/cache"

  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/public/upload"

  driver: gd
  cache: default
  data_loader: default
  default_image: null
  twig:
    mode: legacy
  default_filter_set_settings:
    quality: 100
    jpeg_quality: ~
    png_compression_level: ~
    png_compression_filter: ~
    animated: false
    format: webp
    cache: default
    data_loader: ~
    default_image: null
    filters: []
    post_processors: []
  controller:
    filter_action: liip_imagine.controller:filterAction
    filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    redirect_response_code: 302
  webp:
    generate: true
    quality: 100
    cache: ~
    data_loader: ~
    post_processors: []
  filter_sets:
    # Prototype
    name:
      quality: 100
      jpeg_quality: ~
      png_compression_level: ~
      png_compression_filter: ~
      animated: false
      format: ~
      cache: ~
      data_loader: ~
      default_image: null
      filters:
        # Prototype
        name: []

      post_processors:
        # Prototype
        name: []
